### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by gibster** [alfredh/reicec#1]
Seems to be missing /#include <rew.h>

and has some prototype problems (maybe from rew.h?)

$ make
  CC      build-i686/src/main.o
In file included from src/main.c:12:0:
src/reicec.h:55:16: warning: 'struct trice_conf' declared inside parameter list
   const struct trice_conf _conf);
                ^
src/reicec.h:55:16: warning: its scope is only this definition or declaration, which is probably not what you want
src/main.c:33:15: error: variable 'conf' has initializer but incomplete type
 static struct trice_conf conf = {0, 0};
               ^
src/main.c:33:34: warning: excess elements in struct initializer
 static struct trice_conf conf = {0, 0};
                                  ^
src/main.c:33:34: note: (near initialization for 'conf')
src/main.c:33:37: warning: excess elements in struct initializer
 static struct trice_conf conf = {0, 0};
                                     ^
src/main.c:33:37: note: (near initialization for 'conf')
src/main.c: In function 'tcp_estab_handler':
src/main.c:55:35: warning: passing argument 3 of 'agent_alloc' from incompatible pointer type [-Wincompatible-pointer-types]
  err = agent_alloc(&cli->ag, cli, &conf);
                                   ^
In file included from src/main.c:12:0:
src/reicec.h:54:5: note: expected 'const struct trice_conf *' but argument is of type 'struct trice_conf *'
 int agent_alloc(struct agent *_agp, struct reicec _cli,
     ^
src/main.c: In function 'main':
src/main.c:436:4: error: invalid use of undefined type 'struct trice_conf'
    conf.debug = true;
    ^
src/main.c:474:4: error: invalid use of undefined type 'struct trice_conf'
    conf.trace = true;
    ^
Makefile:49: recipe for target 'build-i686/src/main.o' failed
make: *_\* [build-i686/src/main.o] Error 1

**Comment by alfredh** [comment]
you need to install libre and librew.

I just pushed a small fix. Can you try master HEAD plz?

**Comment by gibster** [comment]
Ah I could have seen that myself :) Thanks for the heads up - it compiled fine now!

**Comment by gibster** [comment]
Would love a command line example in the documents if possible. Running it as:

$ ./reicec.exe -u -t -4 -D -X -L -C -U demo -P secret -S 192.168.1.70 -T 192.168.1.70 -c 192.168.1.75
stun-server: 192.168.1.70
TURN-server: 192.168.1.70
connecting to 192.168.1.75:9000..
ICE agent running in client-mode
Control channel closed (unknown error)
Bye for now

this is from 192.168.1.76

and running reicec on 192.168.1.75 in server mode ... 

That should do something right or am I missing something?

Restund is running on 192.168.1.70  

Thanks
